### ISSUE TITLE
VaspNotFinished exceptions don't seem to work

### ISSUE THREAD

**Issue by jboes** [jkitchin/jasp#21]
Catching 'VaspNotFinished' exceptions doesn't work as I would expect it to. For exmple, the code will not print the corresponding statement requested in the following code:

with jasp('{0}/random/Pd{1}'.format(test,i)) as calc:
            try:
                calc.calculate()
            except(VaspQueued,VaspSubmitted):
                print 'job {0}/random/Pd{1} in que'.format(test,i) 
            except(VaspNotFinished):
                print 'job {0}/random/Pd{1} incomplete'.format(test,i)

Instead the calculation stops and does not continue through the loop.

**Comment by prtkm** [comment]
Thanks to Jake, I seem to have somewhat patched this in these two commits:

https://github.com/prtkm/jasp/commit/af492bd2fa7c05c6f8a28ae551e1e44bf1d2c587

https://github.com/prtkm/jasp/commit/96f18a08b7928397cae8c57ad9d1ba11109f83c3

The idea is to run like,
    with jasp(wd, supress_err=True) as calc:
       
If a VaspNotFinished is found, the error is supressed and calc=None is returned. Any operations on this new calc will raise an AttributeError, which can be easily caught. We could also have skipped returning a calc entriely with __exit__  returning True, but I don't think this is ideal for looping over directories. 

It's probably an ugly way to fix it, maybe you guys have suggestions to improve it?

**Comment by jboes** [comment]
This is not ideal, since all error types raised in the context manager are simply suppressed without further feedback. This does not allow unique exceptions to be handled within the code block.

This method also catches AttributeError exceptions blindly, which, although functional in this instance, is bad practice.

See proposed pull request for how I believe this should be handled, at least for now:
https://github.com/jkitchin/jasp/pull/29

From what I can tell, the only way to avoid the additional if statement is if python would support __enter__() being allowed to skip the statement. This has been previously proposed, and rejected:
http://bison-patches-gnu.git.net/python-dev/msg02065.html

**Comment by prtkm** [comment]
It only supresses the VaspNotFinishedError, and only when you tell it to supress the error. It is also logged in the debug. Neither of the two ways are ideal. The body of you context manager will almost always try to do some operations using the calculator attributes, so the AttributeError makes sense in this case.

The additional if statement makes it kinda ugly. Also, on finding an error, when you return self in __enter__, it returns the context_manager__ (self) as calc, which doesn't make sense. 

One way not to raise the Attribute error and avoid using the if syntax might be to supress VaspNotFinished in __enter__ and re-raise it in the __exit__.

**Comment by jboes** [comment]
You're right, neither is appropriate. Sorry for offending you.

**Comment by prtkm** [comment]
Ok, I changed it so all exceptions are raised in the body of the context manager. I think it works, with the normal syntax, ie 

with jasp(wd) as calc:
  try: 
       do something
   except(VaspNotFinished, VaspSubmitted, VaspQueued):
        do something else


https://github.com/prtkm/jasp/commit/52e224ed5939cea2ddc7ad63df6bd3329e5be7e9

Not sure if this broke anything else though!

**Comment by jkitchin** [comment]
I am closing this issue. If there are still residual exceptions on __enter__, let's open them in new issues.
