### ISSUE TITLE
Error catching automatic nbands changes when running in parallel

### ISSUE THREAD

**Issue by prtkm** [jkitchin/jasp#25]
Hi John,

I found that sometimes when running in parallel, and using the default value of NPAR,  vasp automatically changes the value of nbands. Due to this jasp thinks that the int_params have changed (https://github.com/jkitchin/jasp/blob/master/jasp/jasp_extensions.py#L316) and resubmits the calculation, even though we might already have the correct output (though computationally inefficient).  It might be a good idea to check in the OUTCAR if this is the case, and give an informative warning, rather than restarting the calculation.

|      The number of bands has been changed from the values supplied          |
|      in the INCAR file. This is a result of running the parallel version.   |
|      The orbitals not found in the WAVECAR file will be initialized with    |
|      random numbers, which is usually adequate. For correlated              |
|      calculations, however, you should redo the groundstate calculation.    |
|      I found NBANDS    =        6  now  NBANDS  =       8

**Comment by jkitchin** [comment]
Can you send me a script that causes this behavior?

**Comment by prtkm** [comment]
#+BEGIN_SRC python
from ase import Atoms, Atom
from jasp import *
import numpy as np
np.set_printoptions(precision=3, suppress=True)

JASPRC['queue.nprocs'] = 8 # No. of cores to use
JASPRC['queue.q'] = 'short'
JASPRC['queue.pe'] = 'mpi-8'

co = Atoms([Atom('C',[0,   0, 0]),
            Atom('O',[1.2, 0, 0])],
            cell=(6., 6., 6.))

with jasp('molecules/simple-co', #output dir
          xc='PBE',  # the exchange-correlation functional
          nbands=6,  # number of bands
          encut=350, # planewave cutoff
          ismear=1,  # Methfessel-Paxton smearing
          sigma=0.01,# very small smearing factor for a molecule
          atoms=co) as calc:
    print 'energy = {0} eV'.format(co.get_potential_energy())
    print co.get_forces()
#+END_SRC

I didn't spend too much time worrying about this because it usually works fine when you set npar or ncore with a parallel job.

**Comment by jkitchin** [comment]
what version of vasp is that from? I see the problem, but not the warning
in the OUTCAR


John

-----------------------------------
Professor John Kitchin
Doherty Hall A207F
Department of Chemical Engineering
Carnegie Mellon University
Pittsburgh, PA 15213
412-268-7803
@johnkitchin
http://kitchingroup.cheme.cmu.edu

**Comment by prtkm** [comment]
I've tried 5.2.12 and 5.3.5. It usually gives two warnings .....

vasp.5.3.5 31Mar14 (build Aug 28 2014 22:04:02) complex                        
  
 executed on             LinuxIFC date 2015.01.08  15:51:40
 running on    8 total cores
 distrk:  each k-point on    8 cores,    1 groups
 distr:  one band on NCORES_PER_BAND=   1 cores,    8 groups


--------------------------------------------------------------------------------------------------------


 INCAR:
 POTCAR:    PAW_PBE C 08Apr2002                   
 POTCAR:    PAW_PBE O 08Apr2002                   

 ----------------------------------------------------------------------------- 
|                                                                             |
|           W    W    AA    RRRRR   N    N  II  N    N   GGGG   !!!           |
|           W    W   A  A   R    R  NN   N  II  NN   N  G    G  !!!           |
|           W    W  A    A  R    R  N N  N  II  N N  N  G       !!!           |
|           W WW W  AAAAAA  RRRRR   N  N N  II  N  N N  G  GGG   !            |
|           WW  WW  A    A  R   R   N   NN  II  N   NN  G    G                |
|           W    W  A    A  R    R  N    N  II  N    N   GGGG   !!!           |
|                                                                             |
|      For optimal performance we recommend to set                            |
|        NCORE= 4 - approx SQRT( number of cores)                             |
|      NCORE specifies how many cores store one orbital (NPAR=cpu/NCORE).     |
|      This setting can  greatly improve the performance of VASP for DFT.     |
|      The default, NPAR=number of cores might be grossly inefficient         |
|      on modern multi-core architectures or massively parallel machines.     |
|      Do your own testing !!!!                                               |
|      Unfortunately you need to use the default for GW and RPA calculations. |
|      (for HF NCORE is supported but not extensively tested yet)             |
|                                                                             |
 ----------------------------------------------------------------------------- 

and ....

 Subroutine IBZKPT returns following result:
 ===========================================
 
 Found      1 irreducible k-points:
 
 Following reciprocal coordinates:
            Coordinates               Weight
  0.000000  0.000000  0.000000      1.000000
 
 Following cartesian coordinates:
            Coordinates               Weight
  0.000000  0.000000  0.000000      1.000000
 

 ----------------------------------------------------------------------------- 
|                                                                             |
|           W    W    AA    RRRRR   N    N  II  N    N   GGGG   !!!           |
|           W    W   A  A   R    R  NN   N  II  NN   N  G    G  !!!           |
|           W    W  A    A  R    R  N N  N  II  N N  N  G       !!!           |
|           W WW W  AAAAAA  RRRRR   N  N N  II  N  N N  G  GGG   !            |
|           WW  WW  A    A  R   R   N   NN  II  N   NN  G    G                |
|           W    W  A    A  R    R  N    N  II  N    N   GGGG   !!!           |
|                                                                             |
|      The number of bands has been changed from the values supplied          |
|      in the INCAR file. This is a result of running the parallel version.   |
|      The orbitals not found in the WAVECAR file will be initialized with    |
|      random numbers, which is usually adequate. For correlated              |
|      calculations, however, you should redo the groundstate calculation.    |
|      I found NBANDS    =        6  now  NBANDS  =       8                   |
|                                                                             |
 -----------------------------------------------------------------------------

**Comment by jkitchin** [comment]
ok, thanks. I was using an older version for the neb stuff. I will see if I
can get a newer one.

John

-----------------------------------
Professor John Kitchin
Doherty Hall A207F
Department of Chemical Engineering
Carnegie Mellon University
Pittsburgh, PA 15213
412-268-7803
@johnkitchin
http://kitchingroup.cheme.cmu.edu

**Comment by jkitchin** [comment]
I think this is fixed now. it was a little complicated. hopefully nothing new is broken!
