### ISSUE TITLE
local variable 'self' referenced before assignment

### ISSUE THREAD

**Issue by prtkm** [jkitchin/jasp#27]
Hi John,

I just merged your recent changes and it looks like some things are broken. At https://github.com/jkitchin/jasp/blob/master/jasp/jasp.py#L132 you reference self before you it is created at https://github.com/jkitchin/jasp/blob/master/jasp/jasp.py#L212. 

Prateek

**Comment by jkitchin** [comment]
thanks!

**Comment by prtkm** [comment]
Actually, the new commit still won't work, because self is only created if the jobid file doesnt exist (https://github.com/jkitchin/jasp/blob/master/jasp/jasp.py#L200). Which means an exception will be thrown here if jobid has been deleted (https://github.com/jkitchin/jasp/blob/master/jasp/jasp.py#L312). There will also probably be an undesired conflict with the elif statement here: https://github.com/jkitchin/jasp/blob/master/jasp/jasp.py#L322. 

It is probably best to add these as attributes to calc just before the return statement (https://github.com/jkitchin/jasp/blob/master/jasp/jasp.py#L360) or just delete the CHGCAR and WAVECAR without using attributes at all, i.e

    if (not keep_chgcar
        and os.path.exists('CHGCAR')):
        os.unlink('CHGCAR')

**Comment by jkitchin** [comment]
ok, take2 new commit pushed.;)

**Comment by prtkm** [comment]
That still didn't fix it.

The problem is that the calculator attributes are reset depending on the state of the calculation. We only want to delete the chgcar and the wavecar if:

1. The calculation has finished running and we are looking at it for the first time

2. We are looking at some old calculation where the chgcar and wavecar files still exist (We probably need to be careful here, a default setting of false might lead to undesired instances of files being removed upon reuse of the calculator even though they were orignially kept).

I seemed to have fixed his here:

https://github.com/prtkm/jasp/commit/32984ab1a6fb6bd64cb67334e38f35d37d32f1dd

I'm not sure about the advantage of these attributes over setting vasp keywords like lwave = False or lcharg = False. Maybe deleting files after using information from these files in some way?

**Comment by prtkm** [comment]
Ok, the new commit where you fix the indentation works. Looks like I was overthinking how to set the attributes and added some redundant code!

**Comment by jkitchin** [comment]
Thanks for staying on top of these. I have decided to take these back out
after all. I forgot about the lwave and lcharg tags. I haven't figured out
how to make them be default without breaking old calculations though. It
looks like neb is working for me again!

John

-----------------------------------
Professor John Kitchin
Doherty Hall A207F
Department of Chemical Engineering
Carnegie Mellon University
Pittsburgh, PA 15213
412-268-7803
@johnkitchin
http://kitchingroup.cheme.cmu.edu

**Comment by prtkm** [comment]
Great! Does sorting the atoms during neb work ok for you? I recall I had to replace the code at https://github.com/jkitchin/jasp/blob/master/jasp/jasp_neb.py#L118 by updated code in ase.calculators.vasp (https://trac.fysik.dtu.dk/projects/ase/browser/trunk/ase/calculators/vasp.py?rev=4028#L449) to get it to work for me.

**Comment by jkitchin** [comment]
hm.. The first result was not good. I just replaced that block of code, we
will see if that fixes it!

John

-----------------------------------
Professor John Kitchin
Doherty Hall A207F
Department of Chemical Engineering
Carnegie Mellon University
Pittsburgh, PA 15213
412-268-7803
@johnkitchin
http://kitchingroup.cheme.cmu.edu
