### ISSUE TITLE
Better handling of restarts from unconverged calculations

### ISSUE THREAD

**Issue by prtkm** [jkitchin/jasp#34]
I am opening this issue separately, because the issue where I had initially brought this up is now closed.

Original message below:

On the subject of elegant syntax, I wanted to ask what the best way to not automatically restart finished but unconverged calculations is. There are multiple reasons that one would want to do this.

Examples:

We are doing an geometry optimization and the calc moves towards an undesirable geometry due to a bad initial guess, or it requires a less stringent ediffg value.

SCF calculations with lwave and lcharg set as false (to not write wavecar and chgcar files) will always redo the same unconverged calc.

The only way I can think of to do this is:

try:
if calc.converged:
do something
else:
do something else

except (VaspSubmitted, VaspQueued, VaspNotFinished):
do something else'

Checking if a calc is converged everytime is tedious. Maybe its more convenient to raise a VaspNotConverged error, and ask the user if a restart is desired?

For example something like:

try:
do something
except (VaspSubmitted, VaspQueued, VaspNotFinished):
do something else
except VaspNotConverged:
calc.set_restart_unconverged(True)
calc.calculate()

**Comment by jkitchin** [comment]
A VaspNotConverged exception is probably the way to do this. It is a tough call though. usually you want it to restart, except when you don't ;)

**Comment by prtkm** [comment]
I usually use fairly high values of nsw and nelm. And in my case, the systems are such that sometimes adsorbates move away from the site you are testing. Sometimes a restart helps, but often not so.

Maybe set we could set a desired restart behavior in JASPRC ? I'll try fixing this over the weekend.

**Comment by jkitchin** [comment]
Something in Jason would be a good way to let users do this with default and job specific options.

On February 20, 2015, at 10:02 PM, Prateek Mehta <notifications@github.com> wrote:

I usually use fairly high values of nsw and nelm. And in my case, the systems are such that sometimes adsorbates move away from the site you are testing. Sometimes a restart helps, but often not so.

Maybe set we could set a desired restart behavior in JASPRC ? I'll try fixing this over the weekend.

**Comment by prtkm** [comment]
Ok great. I'll try to get this done.

**Comment by prtkm** [comment]
This turned out to be a pretty straightforward fix.

https://github.com/prtkm/jasp/commit/6670ef8620b057755c25e40110643d9df480db72
