### ISSUE TITLE
BEEF calculations malfunction when requesting multiple processors

### ISSUE THREAD

**Issue by jboes** [jkitchin/jasp#35]
I am getting the following error when running BEEF calculations with multiple processors:

```
 VASP needs to be linked against libbeef for
 Bayesian error estimation functional support.
 libbeef sources and binaries can be downloaded from suncat.stanford.edu
```

This seems to be true for all BEEF calculations.

**Comment by jkitchin** [comment]
You are probably using the wrong binary. Make sure you are using
*vasp-vtst-parallel-beef-vaspsol*

*This one: * *vasp-vtst-parallel-beef*
*does not work and gives your error.*

John

-----------------------------------
Professor John Kitchin
Doherty Hall A207F
Department of Chemical Engineering
Carnegie Mellon University
Pittsburgh, PA 15213
412-268-7803
@johnkitchin
http://kitchingroup.cheme.cmu.edu

**Comment by jboes** [comment]
The environment variable is correct:

```javascript
[jboes@gilgamesh BEEF-multicore]$ echo $VASP_PARALLEL
/opt/kitchingroup/vasp-5.3.5/bin/vasp-vtst-parallel-beef-vaspsol
```

Unless the old binary is hard coded in somewhere, that doesn't seem to be it. I will try again after my queue has cleared.

**Comment by jkitchin** [comment]
it might be hardcoded in a jasprc somewhere.

John

-----------------------------------
Professor John Kitchin
Doherty Hall A207F
Department of Chemical Engineering
Carnegie Mellon University
Pittsburgh, PA 15213
412-268-7803
@johnkitchin
http://kitchingroup.cheme.cmu.edu
