### ISSUE TITLE
Added function to get the number of relaxation steps

### ISSUE THREAD

**Issue by prtkm** [jkitchin/jasp#36]
Strangely, ase.calculators.vasp has a function to return the number of scf iterations (get_number_of_iterations), but no equivalent function for the number of ionic steps. I added it here.

https://github.com/prtkm/jasp/blob/master/jasp/jasp_extensions.py#L1178

**Comment by jkitchin** [comment]
Thanks. I added this to jasp. 
https://github.com/jkitchin/jasp/commit/898992de3fde8cee40779f5500053e45eedc36bd

You can make these pull requests too.

**Comment by prtkm** [comment]
I have thought about making pull requests for issues such as these. However, my jasp_extensions file contains changes for to work with SGE scheduler, which you probably don't want to merge. I this will create a conflict while merging, which you will have to resolve by hand. I just thought it might be simpler to copy small changes and recommit them.

Apparently there is a way to partially merge pull requests, using something like git-cherry-pick (http://git-scm.com/docs/git-cherry-pick), which I was unaware of.

**Comment by jkitchin** [comment]
I have cherry picked before, but it was a little confusing. I am find
with copying small changes in.

Prateek Mehta writes:

> I have thought about making pull requests for issues such as these. However, my jasp_extensions file contains changes for to work with SGE scheduler, which you probably don't want to merge. I this will create a conflict while merging, which you will have to resolve by hand. I just thought it might be simpler to copy small changes and recommit them.
>
> Apparently there is a way to partially merge pull requests, using something like git-cherry-pick (http://git-scm.com/docs/git-cherry-pick), which I was unaware of.
>
>
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/jkitchin/jasp/issues/36#issuecomment-77194487

--
Professor John Kitchin
Doherty Hall A207F
Department of Chemical Engineering
Carnegie Mellon University
Pittsburgh, PA 15213
412-268-7803
@johnkitchin
http://kitchingroup.cheme.cmu.edu
