### ISSUE TITLE
Error message raised for finished vibrational calculations

### ISSUE THREAD

**Issue by prtkm** [jkitchin/jasp#37]
Calculations with ibrion=6 (e.g. vibrational calculations) will print an error message for converged calculations, because the line "reached required accuracy' is not in the OUTCAR (atleast in my vasp version). 

The line that causes this is here:
https://github.com/jkitchin/jasp/blob/master/jasp/jasp_extensions.py#L815

Here is the sample output from an example from dft-book

from ase import Atoms, Atom
from jasp import *
import ase.units

atoms = Atoms([Atom('H', [0.5960812,  -0.7677068,   0.0000000]),
               Atom('O', [0.0000000,   0.0000000,   0.0000000]),
               Atom('H', [0.5960812,   0.7677068,   0.0000000])],
               cell=(8, 8, 8))
atoms.center()

with jasp('molecules/h2o_vib',
          xc='PBE',
          encut=400,
          ismear=0,    # Gaussian smearing
          ibrion=6,    # finite differences with symmetry
          nfree=2,     # central differences (default)
          potim=0.015, # default as well
          ediff=1e-8,  # for vibrations you need precise energies
          nsw=1,       # Set to 1 for vibrational calculation
          atoms=atoms) as calc:

    print 'Forces'
    print '======'
    print atoms.get_forces()
    print
    # vibrational energies are in eV
    energies, modes = calc.get_vibrational_modes()
    print 'energies\n========'
    for i, e in enumerate(energies):
        print '{0:02d}: {1} eV'.format(i, e)
#+END_SRC

#+RESULTS:
#+begin_example
Errors found:
Ions/cell Converged: True

Forces
======
[[ 0.018 -0.033 -0.001]
 [-0.036  0.     0.003]
 [ 0.018  0.033 -0.001]]

energies
========
00: 0.475855778 eV
01: 0.461765195 eV
02: 0.196182161 eV
03: 0.007043227 eV
04: 0.002444899 eV
05: (0.000291928+0j) eV
06: (0.012756409+0j) eV
07: (0.013052354+0j) eV
08: (0.015976715+0j) eV
#+end_example

**Comment by jkitchin** [comment]
Fixed. Thanks for pointing it out!
Prateek Mehta writes:

> Calculations with ibrion=6 (e.g. vibrational calculations) will print an error message for converged calculations, because the line "reached required accuracy' is not in the OUTCAR (atleast in my vasp version).
>
> The line that causes this is here:
> https://github.com/jkitchin/jasp/blob/master/jasp/jasp_extensions.py#L815
>
> Here is the sample output from an example from dft-book
>
> from ase import Atoms, Atom
> from jasp import *
> import ase.units
>
> atoms = Atoms([Atom('H', [0.5960812,  -0.7677068,   0.0000000]),
>                Atom('O', [0.0000000,   0.0000000,   0.0000000]),
>                Atom('H', [0.5960812,   0.7677068,   0.0000000])],
>                cell=(8, 8, 8))
> atoms.center()
>
> with jasp('molecules/h2o_vib',
>           xc='PBE',
>           encut=400,
>           ismear=0,    # Gaussian smearing
>           ibrion=6,    # finite differences with symmetry
>           nfree=2,     # central differences (default)
>           potim=0.015, # default as well
>           ediff=1e-8,  # for vibrations you need precise energies
>           nsw=1,       # Set to 1 for vibrational calculation
>           atoms=atoms) as calc:
>
>     print 'Forces'
>     print '======'
>     print atoms.get_forces()
>     print
>     # vibrational energies are in eV
>     energies, modes = calc.get_vibrational_modes()
>     print 'energies\n========'
>     for i, e in enumerate(energies):
>         print '{0:02d}: {1} eV'.format(i, e)
> #+END_SRC
>
> #+RESULTS:
> #+begin_example
> Errors found:
> Ions/cell Converged: True
>
> Forces
> ======
> [[ 0.018 -0.033 -0.001]
>  [-0.036  0.     0.003]
>  [ 0.018  0.033 -0.001]]
>
> energies
> ========
> 00: 0.475855778 eV
> 01: 0.461765195 eV
> 02: 0.196182161 eV
> 03: 0.007043227 eV
> 04: 0.002444899 eV
> 05: (0.000291928+0j) eV
> 06: (0.012756409+0j) eV
> 07: (0.013052354+0j) eV
> 08: (0.015976715+0j) eV
> #+end_example
>
>
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/jkitchin/jasp/issues/37

--
Professor John Kitchin
Doherty Hall A207F
Department of Chemical Engineering
Carnegie Mellon University
Pittsburgh, PA 15213
412-268-7803
@johnkitchin
http://kitchingroup.cheme.cmu.edu
