### ISSUE TITLE
FERWE, FERDO bug

### ISSUE THREAD

**Issue by prtkm** [jkitchin/jasp#39]
Hi John,

One of the students in the class I'm TAing was trying this code where one sets the occupancies manually for the orbitals using ferwe and ferdo. It appears that ferdo is never read into calc.old_list_params, resulting in automatic job restarts everytime. I suspect this is a bug in ase.calculators.vasp, but I can't figure out where. Code below (I think the procedure is correct).

```python
#+BEGIN_SRC python
from ase import Atoms, Atom
from ase.io import write
from ase.visualize import view
from jasp import *

JASPRC['queue.q'] = 'short'

O=Atoms([Atom('O',[0.,0.,0.],magmom=2)],
            cell=(8,9,10))

with jasp('molecules/simple-Onosym-6',
          xc='PBE',
          nbands=8,
          encut=400,
          ismear=-2,
          ispin=2,
          sigma=0.01,
          ferwe=[1,1,1,1,0,0,0,0],
          ferdo=[1,1,0,0,0,0,0,0],
          atoms=O) as calc:
          #debug=logging.DEBUG) as calc:
    #calc.calculate()
    print calc.old_list_params['ferdo']
    print calc.list_params['ferdo']
    print calc.old_list_params['ferwe']
    print calc.list_params['ferwe']
#+END_SRC
```
#+RESULTS:
: []
: [1, 1, 0, 0, 0, 0, 0, 0]
: [1.0, 1.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0]
: [1, 1, 1, 1, 0, 0, 0, 0]

**Comment by jkitchin** [comment]
hmm.. Around line 1323 in ase.calculators.vasp, it looks like ferdo is
not set at all from incar, but ferwe is. I guess ferdo needs to be added
to that

looks like some tests might be in order.

I pushed a fix for that to ase. you might see if that fixes the issue.

Prateek Mehta writes:

> Hi John,
>
> One of the students in the class I'm TAing was trying this code where one sets the occupancies manually for the orbitals using ferwe and ferdo. It appears that ferwe is never read into calc.old_list_params, resulting in automatic job restarts everytime. I suspect this is a bug in ase.calculators.vasp, but I can't figure out where. Code below (I think the procedure is correct).
>
> #+BEGIN_SRC python
> from ase import Atoms, Atom
> from ase.io import write
> from ase.visualize import view
> from jasp import *
>
> JASPRC['queue.q'] = 'short'
>
> O=Atoms([Atom('O',[0.,0.,0.],magmom=2)],
>             cell=(8,9,10))
>
> with jasp('molecules/simple-Onosym-6',
>           xc='PBE',
>           nbands=8,
>           encut=400,
>           ismear=-2,
>           ispin=2,
>           sigma=0.01,
>           ferwe=[1,1,1,1,0,0,0,0],
>           ferdo=[1,1,0,0,0,0,0,0],
>           atoms=O) as calc:
>           #debug=logging.DEBUG) as calc:
>     #calc.calculate()
>     print calc.old_list_params['ferdo']
>     print calc.list_params['ferdo']
>     print calc.old_list_params['ferwe']
>     print calc.old_list_params['ferwe']
> #+END_SRC
>
> #+RESULTS:
> : []
> : [1, 1, 0, 0, 0, 0, 0, 0]
> : [1.0, 1.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0]
> : [1.0, 1.0, 1.0, 0.0, 0.0, 0.0, 0.0, 0.0]
>
>
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/jkitchin/jasp/issues/39

--
Professor John Kitchin
Doherty Hall A207F
Department of Chemical Engineering
Carnegie Mellon University
Pittsburgh, PA 15213
412-268-7803
@johnkitchin
http://kitchingroup.cheme.cmu.edu

**Comment by prtkm** [comment]
Ok, that fixed it. But it comes with the cost of having an old copy of the ase.trajectory and a new copy of ase.calculators.vasp for everything to fully work. ;)
