### ISSUE TITLE
new ase trajectory parser breaks jaspsum

### ISSUE THREAD

**Issue by prtkm** [jkitchin/jasp#40]
The trunk version recently introduced a new trajectory module to replace the old pickleTrajectory

**Comment by jkitchin** [comment]
How does it break jaspsum?

**Comment by jkitchin** [comment]
I committed a new fix to ase.calculators.vasp that might fix this. at least I can run jaspsum -t on a relaxation and  get it to work.

**Comment by prtkm** [comment]
Thanks. jaspsum -t now works. Does jaspsum -p work for you? ase.visualize.view seems to be broken for me leading to the error below?

>>> view(molecule('CO'))
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/afs/crc.nd.edu/user/p/pmehta1/ase-devel/ase/ase/visualize/__init__.py", line 49, in view
    write(fd, atoms, format=format)
  File "/afs/crc.nd.edu/user/p/pmehta1/ase-devel/ase/ase/io/__init__.py", line 586, in write
    write(filename, images, **kwargs)
  File "/afs/crc.nd.edu/user/p/pmehta1/ase-devel/ase/ase/io/trajectory.py", line 282, in write_trajectory
    trj = TrajectoryWriter(filename, mode='w')
  File "/afs/crc.nd.edu/user/p/pmehta1/ase-devel/ase/ase/io/trajectory.py", line 65, in __init__
    self._open(filename, mode)
  File "/afs/crc.nd.edu/user/p/pmehta1/ase-devel/ase/ase/io/trajectory.py", line 71, in _open
    self.backend = affopen(filename, mode, tag='ASE-Trajectory')
  File "/afs/crc.nd.edu/user/p/pmehta1/ase-devel/ase/ase/io/aff.py", line 69, in affopen
    return Writer(filename, mode, tag)
  File "/afs/crc.nd.edu/user/p/pmehta1/ase-devel/ase/ase/io/aff.py", line 112, in __init__
    fd = open(fd, 'wb')
TypeError: coercing to Unicode: need string or buffer, file found

**Comment by jkitchin** [comment]
I also get that error, and reported it on the mailing list. the issue is a
file descriptor and not a filename is passed to the write_trajectory
function.

John

-----------------------------------
Professor John Kitchin
Doherty Hall A207F
Department of Chemical Engineering
Carnegie Mellon University
Pittsburgh, PA 15213
412-268-7803
@johnkitchin
http://kitchingroup.cheme.cmu.edu

**Comment by prtkm** [comment]
Ah, now the error message makes sense. Thanks for reporting it. Is this the ase-users mailing list?

**Comment by jkitchin** [comment]
yes, the ase-users list.

Prateek Mehta writes:

> Ah, now the error message makes sense. Thanks for reporting it. Is this the ase-users mailing list?
>
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/jkitchin/jasp/issues/40#issuecomment-84383709

--
Professor John Kitchin
Doherty Hall A207F
Department of Chemical Engineering
Carnegie Mellon University
Pittsburgh, PA 15213
412-268-7803
@johnkitchin
http://kitchingroup.cheme.cmu.edu

**Comment by prtkm** [comment]
Apparently, they seem to have fixed view, but I still get an error when a calculator is attached.

**Comment by prtkm** [comment]
Apparently they seem to have fixed it, but I still get an error when view is used with the jasp calculator attached due to the redefined get_dipole_moment method in jasp (https://github.com/jkitchin/jasp/blob/master/jasp/volumetric_data.py#L116). It takes one argument (self) in jasp but two in ase.calculators.vasp (self, atoms).
Due to this, calc.read_dipole() and calc.get_dipole_moment() give two different answers too.

Error below,
  
File "/afs/crc.nd.edu/user/p/pmehta1/jasp/jasp/bin/jaspsum", line 86, in <module>
    view(atoms)
  File "/afs/crc.nd.edu/user/p/pmehta1/ase-devel/ase/ase/visualize/__init__.py", line 48, in view
    write(filename, atoms, format=format)
  File "/afs/crc.nd.edu/user/p/pmehta1/ase-devel/ase/ase/io/__init__.py", line 586, in write
    write(filename, images, **kwargs)
  File "/afs/crc.nd.edu/user/p/pmehta1/ase-devel/ase/ase/io/trajectory.py", line 286, in write_trajectory
    trj.write(atoms)
  File "/afs/crc.nd.edu/user/p/pmehta1/ase-devel/ase/ase/io/trajectory.py", line 137, in write
    allow_calculation=False)
  File "/afs/crc.nd.edu/user/p/pmehta1/ase-devel/ase/ase/io/trajectory.py", line 307, in get_property
    result = getattr(self.calc, method)(atoms)
TypeError: get_dipole_moment() takes exactly 1 argument (2 given)

**Comment by jkitchin** [comment]
hmm. I added an atoms arg to that function. what do you mean by "calc.read_dipole() and calc.get_dipole_moment() " what is different about them? is one "righter" than the other?

**Comment by prtkm** [comment]
ase.calculators.vasp has this function read_dipole() (https://trac.fysik.dtu.dk/projects/ase/browser/trunk/ase/calculators/vasp.py#L1133) which tries to read the dipole moment from the outcar. It will return zeros, while the get_dipole_moment function in jasp will return the actual (which I am assuming are 'righter') values. 

I got confused by this at first before I realized it was redefined in jasp.

Also, get_dipole moment will raise an error if the pseudopotentials are POTCAR.Z files (which is what I have for PW91).  It might be nice to gunzip it into a temporary file like the write_potcar function in ase.calculators.vasp.

**Comment by jkitchin** [comment]
can you make a pull request for POTCAR.Z?

Prateek Mehta writes:

> ase.calculators.vasp has this function read_dipole() (https://trac.fysik.dtu.dk/projects/ase/browser/trunk/ase/calculators/vasp.py#L1133) which tries to read the dipole moment from the outcar. It will return zeros, while the get_dipole_moment function in jasp will return the actual (which I am assuming are 'righter') values.
>
> I got confused by this at first before I realized it was redefined in jasp.
>
> Also, get_dipole moment will raise an error if the pseudopotentials are POTCAR.Z files (which is what I have for PW91).  It might be nice to gunzip it into a temporary file like the write_potcar function in ase.calculators.vasp.
>
>
>
>
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/jkitchin/jasp/issues/40#issuecomment-86260381

--
Professor John Kitchin
Doherty Hall A207F
Department of Chemical Engineering
Carnegie Mellon University
Pittsburgh, PA 15213
412-268-7803
@johnkitchin
http://kitchingroup.cheme.cmu.edu

**Comment by prtkm** [comment]
Ok. On it.

**Comment by jkitchin** [comment]
See https://docs.python.org/2/library/gzip.html. you may not need to actually unzip it.

On March 25, 2015, at 9:55 PM, Prateek Mehta <notifications@github.com> wrote:

Ok. On it.

**Comment by prtkm** [comment]
Tried that, seems to give me an error.

with gzip.open(f, 'rb') as funzip:
    print funzip.read()

  File "<stdin>", line 9, in <module>
  File "/afs/crc.nd.edu/user/p/pmehta1/EPD/lib/python2.7/gzip.py", line 249, in read
    self._read(readsize)
  File "/afs/crc.nd.edu/user/p/pmehta1/EPD/lib/python2.7/gzip.py", line 291, in _read
    self._read_gzip_header()
  File "/afs/crc.nd.edu/user/p/pmehta1/EPD/lib/python2.7/gzip.py", line 185, in _read_gzip_header
    raise IOError, 'Not a gzipped file'
IOError: Not a gzipped file

This seems to work though,

cmdlist = ['zcat', f]
p = Popen(cmdlist, stdin=PIPE, stdout=PIPE, stderr=PIPE,)

out, err = p.communicate()

**Comment by prtkm** [comment]
check https://github.com/jkitchin/jasp/pull/42

**Comment by jkitchin** [comment]
is it a regular zip file? or even a regular file with a .Z extension?
Prateek Mehta writes:

> Tried that, seems to give me an error.
>
> with gzip.open(f, 'rb') as funzip:
>     print funzip.read()
>
>   File "<stdin>", line 9, in <module>
>   File "/afs/crc.nd.edu/user/p/pmehta1/EPD/lib/python2.7/gzip.py", line 249, in read
>     self._read(readsize)
>   File "/afs/crc.nd.edu/user/p/pmehta1/EPD/lib/python2.7/gzip.py", line 291, in _read
>     self._read_gzip_header()
>   File "/afs/crc.nd.edu/user/p/pmehta1/EPD/lib/python2.7/gzip.py", line 185, in _read_gzip_header
>     raise IOError, 'Not a gzipped file'
> IOError: Not a gzipped file
>
> This seems to work though,
>
> cmdlist = ['zcat', f]
> p = Popen(cmdlist, stdin=PIPE, stdout=PIPE, stderr=PIPE,)
>
> out, err = p.communicate()
>
>
>
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/jkitchin/jasp/issues/40#issuecomment-86308367

--
Professor John Kitchin
Doherty Hall A207F
Department of Chemical Engineering
Carnegie Mellon University
Pittsburgh, PA 15213
412-268-7803
@johnkitchin
http://kitchingroup.cheme.cmu.edu

**Comment by prtkm** [comment]
It's a compressed binary file, but it doesn't have the headers in the way
the python gzip library wants. gzip on the command line works fine.
 is it a regular zip file? or even a regular file with a .Z extension?
Prateek Mehta writes:

> Tried that, seems to give me an error.
>
> with gzip.open(f, 'rb') as funzip:
> print funzip.read()
>
> File "<stdin>", line 9, in <module>
> File "/afs/crc.nd.edu/user/p/pmehta1/EPD/lib/python2.7/gzip.py", line
249, in read
> self._read(readsize)
> File "/afs/crc.nd.edu/user/p/pmehta1/EPD/lib/python2.7/gzip.py", line
291, in _read
> self._read_gzip_header()
> File "/afs/crc.nd.edu/user/p/pmehta1/EPD/lib/python2.7/gzip.py", line
185, in _read_gzip_header
> raise IOError, 'Not a gzipped file'
> IOError: Not a gzipped file
>
> This seems to work though,
>
> cmdlist = ['zcat', f]
> p = Popen(cmdlist, stdin=PIPE, stdout=PIPE, stderr=PIPE,)
>
> out, err = p.communicate()
>
>
>
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/jkitchin/jasp/issues/40#issuecomment-86308367

--
Professor John Kitchin
Doherty Hall A207F
Department of Chemical Engineering
Carnegie Mellon University
Pittsburgh, PA 15213
412-268-7803
@johnkitchin
http://kitchingroup.cheme.cmu.edu

—
Reply to this email directly or view it on GitHub
<https://github.com/jkitchin/jasp/issues/40#issuecomment-86491036>.

**Comment by jkitchin** [comment]
weird. Thanks.

Prateek Mehta writes:

> It's a compressed binary file, but it doesn't have the headers in the way
> the python gzip library wants. gzip on the command line works fine.
>  is it a regular zip file? or even a regular file with a .Z extension?
> Prateek Mehta writes:
>
>> Tried that, seems to give me an error.
>>
>> with gzip.open(f, 'rb') as funzip:
>> print funzip.read()
>>
>> File "<stdin>", line 9, in <module>
>> File "/afs/crc.nd.edu/user/p/pmehta1/EPD/lib/python2.7/gzip.py", line
> 249, in read
>> self._read(readsize)
>> File "/afs/crc.nd.edu/user/p/pmehta1/EPD/lib/python2.7/gzip.py", line
> 291, in _read
>> self._read_gzip_header()
>> File "/afs/crc.nd.edu/user/p/pmehta1/EPD/lib/python2.7/gzip.py", line
> 185, in _read_gzip_header
>> raise IOError, 'Not a gzipped file'
>> IOError: Not a gzipped file
>>
>> This seems to work though,
>>
>> cmdlist = ['zcat', f]
>> p = Popen(cmdlist, stdin=PIPE, stdout=PIPE, stderr=PIPE,)
>>
>> out, err = p.communicate()
>>
>>
>>
>>
>> ---
>> Reply to this email directly or view it on GitHub:
>> https://github.com/jkitchin/jasp/issues/40#issuecomment-86308367

--
Professor John Kitchin
Doherty Hall A207F
Department of Chemical Engineering
Carnegie Mellon University
Pittsburgh, PA 15213
412-268-7803
@johnkitchin
http://kitchingroup.cheme.cmu.edu

**Comment by prtkm** [comment]
Hi John,

Do you see plots of the energy trajectory with jaspsum -t? It doesn't seem to plot graphs for me since ase changed the trajectory. If I checkout a revision before the change it seems to work fine.

**Comment by jkitchin** [comment]
No I don't see them. I would raise the issue on the ase mailing list.

**Comment by prtkm** [comment]
Ok, I'll do that, I just wanted to check if it wasn't a matplotlib issue or
something.

I think might just be an issue in xdat2traj in ase.calculators.vasp.

This example calculation on the ase website with the EMT calculator, seems
to show graphs if you visualize the traj file (attached).

https://wiki.fysik.dtu.dk/ase/_downloads/N2Cu.py

**Comment by jkitchin** [comment]
If you can track it down to xdat2trj I can fix that.

On March 31, 2015, at 6:20 PM, Prateek Mehta <notifications@github.com> wrote:

Ok, I'll do that, I just wanted to check if it wasn't a matplotlib issue or
something.

I think might just be an issue in xdat2traj in ase.calculators.vasp.

This example calculation on the ase website with the EMT calculator, seems
to show graphs if you visualize the traj file (attached).

https://wiki.fysik.dtu.dk/ase/_downloads/N2Cu.py

**Comment by prtkm** [comment]
It doesn't look like the calculator or the energies get attached to the atoms objects in the trajectory, which is why we don't see the graphs.

It put in on the mailing list too.

**Comment by jkitchin** [comment]
I see. I am not sure how to fix that. Let me know if you figure it out.

Prateek Mehta writes:

> It doesn't look like the calculator or the energies get attached to the atoms objects in the trajectory, which is why we don't see the graphs.
>
> It put in on the mailing list too.
>
> ---
> Reply to this email directly or view it on GitHub:
> https://github.com/jkitchin/jasp/issues/40#issuecomment-88274908

--
Professor John Kitchin
Doherty Hall A207F
Department of Chemical Engineering
Carnegie Mellon University
Pittsburgh, PA 15213
412-268-7803
@johnkitchin
http://kitchingroup.cheme.cmu.edu
