### ISSUE TITLE
CHG.py vs volumetric_data.py?

### ISSUE THREAD

**Issue by prtkm** [jkitchin/jasp#45]
Hi John,

CHG.py and volumetric_data.py contain the same methods (get_charge_density, get_dipole_moment), which is a little confusing.

 Is one of these files (CHG.py?) deprecated?

**Comment by jkitchin** [comment]
One set should be removed.  Any opinions on which one?

**Comment by prtkm** [comment]
CHG.py. It has fewer functions.

volumetric_data.py seems more recent and I think that's the one that get's used if you do with jasp import *.

**Comment by jkitchin** [comment]
hmm.. it looks like we do not need CHG.py at all then right?

**Comment by prtkm** [comment]
Yes, that's what it looks like.

**Comment by jkitchin** [comment]
ok. I have removed CHG.py
