### ISSUE TITLE
Unusual NEB error with beef-vaspsol binaries

### ISSUE THREAD

**Issue by jboes** [jkitchin/jasp#50]
I'm getting an error where NEB calculations will be removed from the queue just after they begin running.

This only occurs for the 'vasp-vtst-parallel-beef-vaspsol' binaries from what I can tell.

The stdout produces the following message:

``` javascript
 vasp.5.3.5+vtst+beef+vaspsol 31Mar14 (build Feb 19 2015 12:14:39) complex      
  
 vasp.5.3.5+vtst+beef+vaspsol 31Mar14 (build Feb 19 2015 12:14:39) complex      
  
ERROR: the following files does not exist POSCAR
 vasp.5.3.5+vtst+beef+vaspsol 31Mar14 (build Feb 19 2015 12:14:39) complex      
  
ERROR: the following files does not exist POSCAR
ERROR: the following files does not exist POSCAR
```

all other files are empty.

Not sure why this is happening, but the ''vasp-vtst-parallel' binaries seem to operate as excepted, so this a a low priority fix.

**Comment by jkitchin** [comment]
That probably means vtst did not get compiled in to the vasp executable. It isn't really a jasp issue.
